### PR TITLE
CAV-256: Fix notifications IT test

### PR DESCRIPTION
**Pull request by johno1985**
- added scenario for 404 response for notification status
 - minor refactoring

### CODE REVIEW

**Review by mar36tin — DISMISSED** [review]

**Comment by johno1985** [comment]
retest

**Comment by johno1985** [comment]
retest this please

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
test this please

**Review by mar36tin — APPROVED** [review]

**Comment by johno1985** [comment]
rebuild

**Pull request merged**
